# Generated by Django 3.1.3 on 2021-07-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo', '0004_auto_20210714_2131'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cultivos',
            field=models.ManyToManyField(to='cultivo.Cultivo'),
        ),
    ]
