# Generated by Django 3.2.5 on 2021-08-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210715_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='bucket_name',
            new_name='user_tag',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cultivos',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
