# Generated by Django 3.2.5 on 2022-07-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210810_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'AGRICULTOR'), (2, 'ADMIN')], default=1),
        ),
    ]
