# Generated by Django 3.2.5 on 2022-08-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usuario_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'ADMIN'), (2, 'AGRICULTOR')], default=1),
        ),
    ]
