# Generated by Django 3.2.5 on 2022-08-03 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_alter_notificacionrespaldo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionrespaldo',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 2, 19, 39, 33, 88976)),
        ),
    ]
