# Generated by Django 3.2.5 on 2022-08-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0004_alter_notificacionrespaldo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionrespaldo',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
