# Generated by Django 3.2.5 on 2022-08-03 00:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0005_alter_notificacionrespaldo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionrespaldo',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
