# Generated by Django 4.0.6 on 2022-07-17 16:46

from django.db import migrations, models
import django.utils.timezone
import finca.models


class Migration(migrations.Migration):

    dependencies = [
        ('finca', '0002_alter_finca_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='finca',
            name='descripcion',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finca',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=finca.models.get_upload_to_finca),
        ),
    ]
