# Generated by Django 3.2.5 on 2021-08-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
