# Generated by Django 3.1.3 on 2021-07-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='maximo_humedad',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='maximo_radiacion',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='maximo_temperatura',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='minimo_humedad',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='minimo_precipitacion',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='minimo_radiacion',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='minimo_temperatura',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
