# Generated by Django 3.1.3 on 2021-07-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo', '0003_cultivo_maximo_precipitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
