# Generated by Django 3.2.5 on 2021-08-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210810_1524'),
        ('finca', '0002_alter_finca_id'),
        ('cultivo', '0004_auto_20210714_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ListaCultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivo.cultivo')),
                ('id_finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finca.finca')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
        ),
    ]
