# Generated by Django 3.2.5 on 2021-08-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo', '0005_auto_20210810_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listacultivo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
