# Generated by Django 3.2.5 on 2022-08-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo', '0006_alter_listacultivo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listacultivo',
            name='maximo_humedad',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='listacultivo',
            name='maximo_precipitacion',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='listacultivo',
            name='maximo_radiacion',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='listacultivo',
            name='maximo_temperatura',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='listacultivo',
            name='minimo_humedad',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='listacultivo',
            name='minimo_precipitacion',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='listacultivo',
            name='minimo_radiacion',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='listacultivo',
            name='minimo_temperatura',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
